name: Run Tests and Linters
on:
  push:
    branches:
      - master
      - multitenant
  workflow_dispatch:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install chromium-browser

      - run: npm ci

      - name: Run tests
        run: |
          cd cypress
          npm install
          npm test
