name: Slack Notification for new Cypress Reporter Version

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Publish Testerloop Reporter Package"]
    types:
      - completed

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release
        id: release
        uses: actions/github-script@v4
        with:
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const latestRelease = releases.data[0];
            console.log(latestRelease.tag_name);
            core.setOutput('tag_name', latestRelease.tag_name);

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: |
            Build & Publish Testerloop Reporter Package workflow completed successfully.

            Latest Release: *[ ${{ steps.release.outputs.tag_name }} ]* (https://github.com/${{ github.repository }}/releases/latest)
